### ISSUE TITLE
A method to dynamically choose an integral message type to be sent.

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [IYP-Programer-Yeah/MDP#2]
It's useful to have a method of converting dynamic integral values to compile time integral values. This in a sense is a switch case table.

This could be achieved by having a separate module that interprets dynamic integral values to integrally indexed message.

**Comment by rednewt** [comment]
Yes, true

**Comment by rednewt** [comment]
Fuck off

**Comment by rednewt** [comment]
DELETE THIS

**Comment by IYP-Programer-Yeah** [comment]
Multiplexer module was added to this end. This module will multiplex over the given type of message using the dynamic integer included the in the multiplex message.
